apiVersion: apps/v1
kind: Deployment
metadata:
  name: ae-app
spec:
  selector:
    matchLabels:
      app: ae-app
  replicas: 1
  template:
    metadata:
      labels:
        app: ae-app
    spec:
      containers:
      - name: ae-app
        image: aesedeu/gitlab-app:latest
        ports:
        - containerPort: 8000
